### ISSUE TITLE
Measure performance behind proxies

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Performance#186]
# Hosting Models
* Windows Server 2016 
  * Kestrel
  * WebListener
  * IIS + ANCM + Kestrel (https://docs.microsoft.com/en-us/aspnet/core/publishing/iis)
* Ubuntu 16.04 
  * Kestrel
  * nginx + Kestrel (https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction)
  * haproxy + Kestrel (future)
  * apache + Kestrel (future)

# Benchmarks
* Plaintext (pipeline = 16)
* Plaintext (no pipelining)
* JSON
* MvcDbFortunesEf

# Servers
* Azure F4
* On-prem (future)

# Work Items
* SSL and non-SSL for each benchmark
* Make IIS and nginx config as similar as possible

**Comment by GuardRex** [comment]
We're showing devs with IIS/ANCM how to setup IIS with the default IIS module configuration in the *Publishing to IIS doc*. There's a new doc on the horizon that deals with IIS Modules in more detail, including some notes on disabling modules.

The minimal module configuration is to only have the Anonymous Authentication Module and the ANCM configured. I wonder ... and I think other admins will wonder: How much faster is running IIS/ANCM with the minimal module configuration (just those two modules) versus the default module configuration?

I would've tested myself, but I don't have a test rig that can determine the difference. If you're willing to test these two configurations of IIS and there's a significant perf boost to disabling unused modules, I hope to report such test results in the upcoming IIS Modules doc.

**Comment by bangbingsyb** [comment]
There is a big problem of the minimum module configuration proposed here, and only including AnonymousAuthenticationModule and the ANCM will make the performance much worse than the default applicationHost.config in a synthetic benchmark using a very simple app. 

The reason is the missing of UriCacheModule in this configuration. UriCacheModule doesn't have any configuration you can set, so people often forgets its existence. However, it actually helps IIS caches merged configuration at URL level (it is not a response cache, otherwise enabling it in the perf test might sound cheating).  Without this module, IIS has to read and parse configuration for every request, even if they might target to the same URL, and the configuration reading cost is significant in comparison with the rest of request processing for helloworld-style test.

**Comment by guardrex** [comment]
Thanks @bangbingsyb ... We'll talk about it over on https://github.com/aspnet/Docs/pull/2609.

**Comment by guardrex** [comment]
Note for this issue if testing includes a suite where the minimum module config is checked vs. the default module config: We've updated the topic. https://github.com/aspnet/Docs/pull/5873 (should merge around 4/6/2018) https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/modules#minimum-module-configuration

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
